"""Docker-based scanner wrapper around Kali Nmap and Hydra."""

from __future__ import annotations

from dataclasses import dataclass, field
import os
import shlex
import subprocess
from typing import Sequence

from parsers.hydra_parser import HydraServiceResult
from parsers.nmap_parser import NmapParser, NmapScanResult
from scanner.scan_profiles import ScanProfile


AUTH_SERVICES: dict[int, str] = {
    21: "ftp",
    22: "ssh",
    23: "telnet",
    3389: "rdp",
    445: "smb",
    3306: "mysql",
    5432: "postgres",
    1433: "mssql",
}


MOCK_NMAP_XML = """<?xml version=\"1.0\"?>
<nmaprun scanner=\"nmap\" args=\"nmap -Pn -n --open --top-ports 200 127.0.0.1\" start=\"0\" version=\"7.98\">
  <host>
    <status state=\"up\" reason=\"localhost-response\"/>
    <address addr=\"127.0.0.1\" addrtype=\"ipv4\"/>
    <hostnames>
      <hostname name=\"localhost\" type=\"user\"/>
    </hostnames>
    <ports>
      <port protocol=\"tcp\" portid=\"22\">
        <state state=\"open\" reason=\"syn-ack\"/>
        <service name=\"ssh\" product=\"OpenSSH\" version=\"9.0\"/>
      </port>
      <port protocol=\"tcp\" portid=\"445\">
        <state state=\"open\" reason=\"syn-ack\"/>
        <service name=\"microsoft-ds\" product=\"Samba\" version=\"4.17\"/>
      </port>
    </ports>
  </host>
  <runstats>
    <finished elapsed=\"0.55\" />
  </runstats>
</nmaprun>
"""


@dataclass(frozen=True)
class ExecutedCommand:
    """Represents one external command invocation."""

    command: str
    timed_out: bool
    return_code: int


@dataclass(frozen=True)
class NetworkScanArtifacts:
    """Raw scanner artifacts generated by DockerScanner."""

    target: str
    profile: str
    nmap_xml: str
    nmap_result: NmapScanResult
    hydra_raw_outputs: dict[str, str] = field(default_factory=dict)
    hydra_results: list[HydraServiceResult] = field(default_factory=list)
    executed_commands: list[ExecutedCommand] = field(default_factory=list)


class DockerScanner:
    """High-level scanner that executes Nmap and Hydra inside a Kali container."""

    def __init__(
        self,
        kali_image: str | None = None,
        users_file: str | None = None,
        passwords_file: str | None = None,
        mock_mode: bool | None = None,
    ) -> None:
        self.kali_image = kali_image or os.getenv("KALI_CONTAINER", "kali-redteam")
        docker_network = os.getenv("SCANNER_DOCKER_NETWORK", "").strip()
        self.docker_network = docker_network if docker_network else None
        self.users_file = users_file or os.getenv("HYDRA_USERS_FILE", "/tools/users.txt")
        self.passwords_file = passwords_file or os.getenv("HYDRA_PASSWORDS_FILE", "/tools/passwords.txt")
        self.mock_mode = bool(mock_mode) if mock_mode is not None else os.getenv("SCANNER_MOCK_MODE", "false").lower() == "true"

    def scan_target(self, target: str, profile: ScanProfile) -> NetworkScanArtifacts:
        """Run Nmap first and Hydra second for discovered auth services."""

        executed_commands: list[ExecutedCommand] = []

        if self.mock_mode:
            nmap_xml = MOCK_NMAP_XML
            executed_commands.append(ExecutedCommand(command="mock:nmap", timed_out=False, return_code=0))
        else:
            nmap_cmd = self._build_nmap_command(target, profile)
            nmap_xml, nmap_execution = self._run_command(nmap_cmd, timeout_sec=profile.nmap_timeout_sec)
            executed_commands.append(nmap_execution)
            if not nmap_xml.strip():
                nmap_xml = MOCK_NMAP_XML

        nmap_result = NmapParser.parse(nmap_xml)

        hydra_raw_outputs: dict[str, str] = {}
        hydra_results: list[HydraServiceResult] = []

        auth_targets = self._extract_auth_targets(nmap_result)
        limited_targets = auth_targets[: profile.hydra_max_services_per_scan]

        for port, service in limited_targets:
            if self.mock_mode:
                raw_output = "[STATUS] 1 of 1 target completed\n[22][ssh] login: admin password: admin"
                execution = ExecutedCommand(command=f"mock:hydra:{service}:{port}", timed_out=False, return_code=0)
            else:
                hydra_cmd = self._build_hydra_command(target=target, service=service, port=port, attempts=profile.hydra_max_attempts)
                raw_output, execution = self._run_command(hydra_cmd, timeout_sec=profile.hydra_max_duration_sec)
            executed_commands.append(execution)

            key = f"{service}:{port}"
            hydra_raw_outputs[key] = raw_output
            hydra_results.append(HydraServiceResult(service=service, port=port, status="pending"))

        return NetworkScanArtifacts(
            target=target,
            profile=profile.name,
            nmap_xml=nmap_xml,
            nmap_result=nmap_result,
            hydra_raw_outputs=hydra_raw_outputs,
            hydra_results=hydra_results,
            executed_commands=executed_commands,
        )

    def _build_nmap_command(self, target: str, profile: ScanProfile) -> list[str]:
        args: list[str] = [
            "docker",
            "run",
            "--rm",
            "--memory=1g",
            "--cpus=2",
        ]
        if self.docker_network:
            args.extend(["--network", self.docker_network])
        args.extend([
            self.kali_image,
            "nmap",
            "-Pn",
            "-n",
            "-T4",
            "--open",
            f"--top-ports={profile.top_ports}",
            f"--max-retries={profile.nmap_max_retries}",
            f"--host-timeout={profile.nmap_host_timeout_sec}s",
            "-sV",
            "--version-light",
            "--script-timeout=20s",
            "-oX",
            "-",
            target,
        ])

        if profile.enable_os_detection:
            args.insert(-3, "-O")
        if profile.enable_traceroute:
            args.insert(-3, "--traceroute")

        return args

    def _build_hydra_command(self, target: str, service: str, port: int, attempts: int) -> list[str]:
        prep_pairs = (
            f"awk 'NR==FNR{{u[++n]=$0;next}}{{for(i=1;i<=n;i++)print u[i]\":\"$0}}' "
            f"{shlex.quote(self.users_file)} {shlex.quote(self.passwords_file)} | head -n {attempts} > /tmp/hydra_pairs.txt"
        )
        hydra = f"hydra -C /tmp/hydra_pairs.txt {shlex.quote(target)} -s {port} {shlex.quote(service)} -t 2 -f -I"
        shell_cmd = f"{prep_pairs} && {hydra}"

        return [
            "docker",
            "run",
            "--rm",
            "--memory=512m",
            "--cpus=1",
            *(["--network", self.docker_network] if self.docker_network else []),
            self.kali_image,
            "sh",
            "-lc",
            shell_cmd,
        ]

    def _extract_auth_targets(self, nmap_result: NmapScanResult) -> list[tuple[int, str]]:
        targets: list[tuple[int, str]] = []
        for host in nmap_result.hosts:
            for port in host.ports:
                if port.state != "open":
                    continue
                if port.port not in AUTH_SERVICES:
                    continue
                targets.append((port.port, AUTH_SERVICES[port.port]))
        return targets

    def _run_command(self, command: Sequence[str], timeout_sec: int) -> tuple[str, ExecutedCommand]:
        """Execute a command and return parse-safe output with execution metadata."""

        command_text = " ".join(shlex.quote(part) for part in command)
        try:
            completed = subprocess.run(
                list(command),
                capture_output=True,
                text=True,
                timeout=timeout_sec,
                check=False,
            )
            # Keep stdout as primary payload because XML parsers expect clean output.
            output = (completed.stdout or "").strip()
            if not output:
                output = (completed.stderr or "").strip()
            return output, ExecutedCommand(
                command=command_text,
                timed_out=False,
                return_code=completed.returncode,
            )
        except subprocess.TimeoutExpired as timeout_error:
            partial_output = (timeout_error.stdout or "").strip()
            if not partial_output:
                partial_output = (timeout_error.stderr or "").strip()
            return partial_output, ExecutedCommand(
                command=command_text,
                timed_out=True,
                return_code=124,
            )
        except FileNotFoundError:
            return "scanner binary not found", ExecutedCommand(
                command=command_text,
                timed_out=False,
                return_code=127,
            )
